/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocketIndexRouteImport } from './routes/socket/index'
import { Route as SocketIdRouteImport } from './routes/socket/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocketIndexRoute = SocketIndexRouteImport.update({
  id: '/socket/',
  path: '/socket/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocketIdRoute = SocketIdRouteImport.update({
  id: '/socket/$id',
  path: '/socket/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/socket/$id': typeof SocketIdRoute
  '/socket': typeof SocketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/socket/$id': typeof SocketIdRoute
  '/socket': typeof SocketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/socket/$id': typeof SocketIdRoute
  '/socket/': typeof SocketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/socket/$id' | '/socket'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/socket/$id' | '/socket'
  id: '__root__' | '/' | '/socket/$id' | '/socket/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SocketIdRoute: typeof SocketIdRoute
  SocketIndexRoute: typeof SocketIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socket/': {
      id: '/socket/'
      path: '/socket'
      fullPath: '/socket'
      preLoaderRoute: typeof SocketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socket/$id': {
      id: '/socket/$id'
      path: '/socket/$id'
      fullPath: '/socket/$id'
      preLoaderRoute: typeof SocketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SocketIdRoute: SocketIdRoute,
  SocketIndexRoute: SocketIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
